name: ci

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(toJson(github.event.commits), '[ci skip]') && !contains(toJson(github.event.commits), '[skip ci]')
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - run: make lint
      - run: make test
