name: ci

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(toJson(github.event.commits), '[ci skip]') && !contains(toJson(github.event.commits), '[skip ci]')
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: make lint
      - run: make test
