name: ci

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(toJson(github.event.commits), '[ci skip]') && !contains(toJson(github.event.commits), '[skip ci]')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: make lint
      - run: make test
