name: validate renovate.json

on:
  pull_request:

env:
  LOG_LEVEL: debug
  RENOVATE_VERSION: "44.11.4" # renovate: datasource=npm depName=renovate

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*

      - run: npx --yes --ignore-scripts -p "renovate@${RENOVATE_VERSION}" -- renovate-config-validator renovate.json
